import React from 'react';
import AuditProviderList from '../AuditProviderList';
import { storiesOf } from '@storybook/react';
import AdminStore from '../../../../.storybook/store';

const removeAuditProvider = (auditId) => {};
const auditProviderList1 = {
  TotalRecords: 5,
  Results: [
    {
      ProviderAddress: '999 18th St, Denver, CO 80202',
      Type: 'Standard',
      AuditId: 566941,
      Pwid: 'YC7CH',
      Status: 'READY',
      ProviderFullName: 'Cindi T.  Rife (Test Profile), CFMP',
      ClientName: '',
      UserName: 'kgannonjedi+ref1025t@gmail.com',
      AuditedByUsername: 'Test',
      SubmittedByFullName: 'Cindi Rife',
      LastModifiedDate: '2020-09-15T07:11:16.48',
      LastModifiedDateString: 'Thu, Sep 09, 2020',
      LastModifiedTimeString: '11:16 Am',
      LastContactedDate: null,
      ProfileManagerAuditRecord: {
        AuditSection: [
          {
            Id: '8818fd9c-2d34-4de2-9925-42c604396ba6',
            Pwid: 'YC7CH',
            IsProcessed: false,
            SectionName: 'Name - first_name',
            Items: [
              {
                Id: '8818fd9c-2d34-4de2-9925-42c604396ba6',
                ItemId: null,
                IsProcessed: false,
                OriginalValue: 'Cindi',
                ProposedValue: 'C',
                ActionTaken: null,
                Status: null,
                SectionName: 'Name - first_name',
                RequestedDate: '9/3/2020 5:10:03 AM',
                RequestedBy: 'kgannonjedi+ref1025t@gmail.com',
                JoinedAuditItemId: null,
                ProposedEmailValue: null,
              },
            ],
            JoinedAudtItem: null,
          },
          {
            Id: '1a0559a4-0375-4ad1-a75e-a215ab4dd62f',
            Pwid: 'YC7CH',
            IsProcessed: false,
            SectionName: 'Name - last_name',
            Items: [
              {
                Id: '1a0559a4-0375-4ad1-a75e-a215ab4dd62f',
                ItemId: null,
                IsProcessed: false,
                OriginalValue: 'Last',
                ProposedValue: 'R',
                ActionTaken: null,
                Status: null,
                SectionName: 'Name - last_name',
                RequestedDate: '9/3/2020 5:10:03 AM',
                RequestedBy: 'kgannonjedi+ref1025t@gmail.com',
                JoinedAuditItemId: null,
                ProposedEmailValue: null,
              },
            ],
            JoinedAudtItem: null,
          },
          {
            Id: '25378dfc-4211-4128-8e37-c94fb09ee773',
            Pwid: 'YC7CH',
            IsProcessed: false,
            SectionName: 'Name - suffix',
            Items: [
              {
                Id: '25378dfc-4211-4128-8e37-c94fb09ee773',
                ItemId: null,
                IsProcessed: false,
                OriginalValue: 'II',
                ProposedValue: 'Jr.',
                ActionTaken: null,
                Status: null,
                SectionName: 'Name - suffix',
                RequestedDate: '9/3/2020 5:10:03 AM',
                RequestedBy: 'kgannonjedi+ref1025t@gmail.com',
                JoinedAuditItemId: null,
                ProposedEmailValue: null,
              },
            ],
            JoinedAudtItem: null,
          },
          {
            Id: '4ee9021a-a342-45b9-bbd0-81307774772b',
            Pwid: 'YC7CH',
            IsProcessed: false,
            SectionName: 'License',
            Items: [
              {
                Id: '4ee9021a-a342-45b9-bbd0-81307774772b',
                ItemId: null,
                IsProcessed: false,
                OriginalValue: 'AL 55461e',
                ProposedValue: '',
                ActionTaken: null,
                Status: 'DELETE',
                SectionName: 'License - DELETE',
                RequestedDate: '4/10/2020 6:12:47 AM',
                RequestedBy: 'kgannonjedi+ref1025t@gmail.com',
                JoinedAuditItemId: null,
                ProposedEmailValue: null,
              },
            ],
            JoinedAudtItem: null,
          },
          {
            Id: '8c9fd8d8-83fe-42ec-ae27-0be242033cca',
            Pwid: 'YC7CH',
            IsProcessed: false,
            SectionName: 'License',
            Items: [
              {
                Id: '8c9fd8d8-83fe-42ec-ae27-0be242033cca',
                ItemId: null,
                IsProcessed: false,
                OriginalValue: 'CO 987654321111',
                ProposedValue: '',
                ActionTaken: null,
                Status: 'DELETE',
                SectionName: 'License - DELETE',
                RequestedDate: '4/10/2020 6:12:47 AM',
                RequestedBy: 'kgannonjedi+ref1025t@gmail.com',
                JoinedAuditItemId: null,
                ProposedEmailValue: null,
              },
            ],
            JoinedAudtItem: null,
          },
          {
            Id: '4b7a4ac2-cb3e-46c9-889b-7bb03860d1a1',
            Pwid: 'YC7CH',
            IsProcessed: false,
            SectionName: 'License',
            Items: [
              {
                Id: '4b7a4ac2-cb3e-46c9-889b-7bb03860d1a1',
                ItemId: null,
                IsProcessed: false,
                OriginalValue: 'NH ',
                ProposedValue: '',
                ActionTaken: null,
                Status: 'DELETE',
                SectionName: 'License - DELETE',
                RequestedDate: '4/10/2020 6:12:47 AM',
                RequestedBy: 'kgannonjedi+ref1025t@gmail.com',
                JoinedAuditItemId: null,
                ProposedEmailValue: null,
              },
            ],
            JoinedAudtItem: null,
          },
          {
            Id: 'aff01488-fcce-4944-9873-7c576033a22b',
            Pwid: 'YC7CH',
            IsProcessed: false,
            SectionName: 'License',
            Items: [
              {
                Id: 'aff01488-fcce-4944-9873-7c576033a22b',
                ItemId: null,
                IsProcessed: false,
                OriginalValue: '',
                ProposedValue: 'CA ',
                ActionTaken: null,
                Status: 'NEW',
                SectionName: 'License - NEW',
                RequestedDate: '4/10/2020 6:12:47 AM',
                RequestedBy: 'kgannonjedi+ref1025t@gmail.com',
                JoinedAuditItemId: null,
                ProposedEmailValue: null,
              },
            ],
            JoinedAudtItem: null,
          },
          {
            Id: '787daa6b-f21b-46d7-acfe-bb4e1ef4ae0a',
            Pwid: 'YC7CH',
            IsProcessed: false,
            SectionName: 'Education',
            Items: [
              {
                Id: '787daa6b-f21b-46d7-acfe-bb4e1ef4ae0a',
                ItemId: null,
                IsProcessed: false,
                OriginalValue: 'Cu ',
                ProposedValue: '',
                ActionTaken: null,
                Status: 'DELETE',
                SectionName: 'Education - EDUTRA',
                RequestedDate: '4/10/2020 6:46:41 AM',
                RequestedBy: 'kgannonjedi+ref1025t@gmail.com',
                JoinedAuditItemId: null,
                ProposedEmailValue: null,
              },
            ],
            JoinedAudtItem: null,
          },
          {
            Id: '073747a9-70e4-4260-8f0f-055430f6a6a6',
            Pwid: 'YC7CH',
            IsProcessed: false,
            SectionName: 'Education',
            Items: [
              {
                Id: '073747a9-70e4-4260-8f0f-055430f6a6a6',
                ItemId: null,
                IsProcessed: false,
                OriginalValue: '',
                ProposedValue: 'Diploma In Anesthesiology ',
                ActionTaken: null,
                Status: 'NEW',
                SectionName: 'Education - EDUTRA',
                RequestedDate: '4/10/2020 6:46:41 AM',
                RequestedBy: 'kgannonjedi+ref1025t@gmail.com',
                JoinedAuditItemId: '',
                ProposedEmailValue: null,
              },
            ],
            JoinedAudtItem: null,
          },
          {
            Id: '6ffa350b-4c2a-42e0-a27c-8f56f85d4dc2',
            Pwid: 'YC7CH',
            IsProcessed: false,
            SectionName: 'Photo',
            Items: [
              {
                Id: '6ffa350b-4c2a-42e0-a27c-8f56f85d4dc2',
                ItemId: null,
                IsProcessed: false,
                OriginalValue: '',
                ProposedValue: '1',
                ActionTaken: null,
                Status: null,
                SectionName: 'Photo',
                RequestedDate: '8/20/2020 10:51:23 AM',
                RequestedBy: 'kgannonjedi+ref1025t@gmail.com',
                JoinedAuditItemId: null,
                ProposedEmailValue: null,
              },
            ],
            JoinedAudtItem: null,
          },
          {
            Id: '90b7b62c-6522-4114-9aa5-b3554a5252bf',
            Pwid: 'YC7CH',
            IsProcessed: false,
            SectionName: 'AboutMe',
            Items: [
              {
                Id: '90b7b62c-6522-4114-9aa5-b3554a5252bf',
                ItemId: 'About',
                IsProcessed: false,
                OriginalValue:
                  '<strong>Title:</strong> About Cindi Rife (Test Profile)<p>Dr. Cindi&nbsp;Rife, MD is a psychiatry doctor who practices in Upland, PA. He has been practicing for 11 years. Dr. Glushakow is affiliated with Delaware County Memorial Hospital, Crozer - Chester Medical Center, Rife&nbsp;Hospital and Springfield Hospital.</p>',
                ProposedValue:
                  '<strong>Title:</strong> About Cindi Rife (Test Profile)<p>Demo</p>',
                ActionTaken: 'HOLD',
                Status: 'NEW',
                SectionName: 'Biography',
                RequestedDate: '9/3/2020 5:10:11 AM',
                RequestedBy: 'kgannonjedi+ref1025t@gmail.com',
                JoinedAuditItemId: 'About',
                ProposedEmailValue: null,
              },
            ],
            JoinedAudtItem: {
              Id: 'ba4c8e85-e8f1-455b-9c2a-2b7dca5c1a28',
              ItemId: 'About',
              IsProcessed: false,
              OriginalValue:
                '<strong>Title:</strong> About Cindi Rife (Test Profile)<p>Dr. Cindi&nbsp;Rife, MD is a psychiatry doctor who practices in Upland, PA. He has been practicing for 11 years. Dr. Glushakow is affiliated with Delaware County Memorial Hospital, Crozer - Chester Medical Center, Rife&nbsp;Hospital and Springfield Hospital.</p>',
              ProposedValue: 'Deleted',
              ActionTaken: 'HOLD',
              Status: 'DELETE',
              SectionName: 'Biography',
              RequestedDate: '9/3/2020 5:10:11 AM',
              RequestedBy: 'kgannonjedi+ref1025t@gmail.com',
              JoinedAuditItemId: null,
              ProposedEmailValue: null,
            },
          },
          {
            Id: '78979230-4a5a-49a2-9265-c20537d3ec58',
            Pwid: 'YC7CH',
            IsProcessed: false,
            SectionName: 'AboutMe',
            Items: [
              {
                Id: '78979230-4a5a-49a2-9265-c20537d3ec58',
                ItemId: 'CarePhilosophy',
                IsProcessed: false,
                OriginalValue: '',
                ProposedValue:
                  '<p>Dr. Cindi&nbsp;Rife, MD is a psychiatry doctor who practices in Upland, PA. He has been practicing for 11 years. Dr. Glushakow is affiliated with Delaware County Memorial Hospital, Crozer - Chester Medical Center, Rife&nbsp;Hospital and Springfield Hospital.</p>',
                ActionTaken: 'HOLD',
                Status: 'NEW',
                SectionName: 'Care Philosophy',
                RequestedDate: '9/3/2020 5:10:11 AM',
                RequestedBy: 'kgannonjedi+ref1025t@gmail.com',
                JoinedAuditItemId: 'CarePhilosophy',
                ProposedEmailValue: null,
              },
            ],
            JoinedAudtItem: null,
          },
          {
            Id: '224abcc0-a60f-457f-b0de-3b09f1f5a18d',
            Pwid: 'YC7CH',
            IsProcessed: false,
            SectionName: 'AboutMe',
            Items: [
              {
                Id: '224abcc0-a60f-457f-b0de-3b09f1f5a18d',
                ItemId: 'ResponseToPes',
                IsProcessed: false,
                OriginalValue: '<p>testing 123</p>',
                ProposedValue: '<p>Test Response</p>',
                ActionTaken: 'HOLD',
                Status: 'NEW',
                SectionName: 'Response to Patient Satisfaction Surveys',
                RequestedDate: '9/3/2020 5:10:11 AM',
                RequestedBy: 'kgannonjedi+ref1025t@gmail.com',
                JoinedAuditItemId: 'ResponseToPes',
                ProposedEmailValue: null,
              },
            ],
            JoinedAudtItem: {
              Id: '96890014-51c4-4a43-a868-19b477b35b98',
              ItemId: 'ResponseToPes',
              IsProcessed: false,
              OriginalValue: '<p>testing 123</p>',
              ProposedValue: 'Deleted',
              ActionTaken: 'HOLD',
              Status: 'DELETE',
              SectionName: 'Response to Patient Satisfaction Surveys',
              RequestedDate: '9/3/2020 5:10:11 AM',
              RequestedBy: 'kgannonjedi+ref1025t@gmail.com',
              JoinedAuditItemId: null,
              ProposedEmailValue: null,
            },
          },

          {
            Id: '1a0559a4-0375-4ad1-a75e-a665ab4dd62f',
            Pwid: 'YLV2V',
            IsProcessed: false,
            SectionName: 'Video',
            Items: [
              {
                ItemId: null,
                IsProcessed: false,
                OriginalValue:
                  'https://testaws.healthgrades.com/video/00000153-8588-d304-afdf-ddec91bb0000',
                ProposedValue:
                  'https://d2074hyx2donso.cloudfront.net/videos/XYLTS6V/01f53e4a40444e978f6d355f238b42c1.mp4',
                ActionTaken: null,
                Status: null,
                SectionName: 'Video',
                AuditId: 54362,
                VideoDetails: {
                  ModerationResult: [
                    {
                      ModerationLabelName: 'Violence',
                      Timestamp: 5999,
                    },
                    {
                      ModerationLabelName: 'Weapon Violence',
                      Timestamp: 6499,
                    },
                    {
                      ModerationLabelName: 'Violence',
                      Timestamp: 25066,
                    },
                    {
                      ModerationLabelName: 'Weapon',
                      Timestamp: 25566,
                    },
                    {
                      ModerationLabelName: 'Violence',
                      Timestamp: 26066,
                    },
                    {
                      ModerationLabelName: 'Weapon',
                      Timestamp: 26566,
                    },
                    {
                      ModerationLabelName: 'Violence',
                      Timestamp: 27066,
                    },
                    {
                      ModerationLabelName: 'Weapons',
                      Timestamp: 27566,
                    },
                    {
                      ModerationLabelName: 'Weapon Violence',
                      Timestamp: 37566,
                    },
                    {
                      ModerationLabelName: 'Weapon Violence',
                      Timestamp: 38400,
                    },
                  ],
                  VideoTranscript:
                    "Where's friend free? She's at the tower with your little friend Marie Elka. She gave us a message to pass on to you. You have to choose the lesser evil. It's an ultimatum, get it, mm. Mhm. Yeah. Mhm. Okay. Mhm. Uh huh. Yeah. Yeah.",
                  VideoHostCode: 'BRIGHTSPOT',
                },
              },
            ],
            JoinedAudtItem: null,
          },
        ],
        Total: 0,
        HasOneAcceptedAddress: true,
        HasAboutMeAudit: true,
        HasFacilityAudit: false,
      },
    },
    {
      ProviderAddress: '7480 Ziegler Rd, Chattanooga, TN 37421',
      Type: 'Sponsored',
      AuditId: 567721,
      Pwid: 'YLV2V',
      Status: 'READY',
      ProviderFullName: 'Dr. Robert  Mastey, MD',
      ClientName: 'Metro Regional Medical Center Testing and Demo',
      UserName: 'pollyreese@hgweb.com',
      AuditedByUsername: null,
      SubmittedByFullName: 'Polly Reese',
      LastModifiedDate: '2019-08-20T01:45:40.383',
      LastModifiedDateString: 'Thu, Aug 20, 2020',
      LastModifiedTimeString: '01:45 pm',
      LastContactedDate: null,
      ProfileManagerAuditRecord: {
        AuditSection: [
          {
            Id: '8818fd9c-2d34-4de2-9925-42c604396ba6',
            Pwid: 'YLV2V',
            IsProcessed: false,
            SectionName: 'Name - first_name',
            Items: [
              {
                Id: '8818fd9c-2d34-4de2-9925-42c604396ba6',
                ItemId: null,
                IsProcessed: false,
                OriginalValue: 'Robert',
                ProposedValue: 'Robertt',
                ActionTaken: null,
                Status: null,
                SectionName: 'Name - first_name',
                RequestedDate: '9/3/2020 5:10:03 AM',
                RequestedBy: 'kgannonjedi+ref1025t@gmail.com',
                JoinedAuditItemId: null,
                ProposedEmailValue: null,
              },
            ],
            JoinedAudtItem: null,
          },
          {
            Id: '1a0559a4-0375-4ad1-a75e-a215ab4dd62f',
            Pwid: 'YLV2V',
            IsProcessed: false,
            SectionName: 'Name - last_name',
            Items: [
              {
                Id: '1a0559a4-0375-4ad1-a75e-a215ab4dd62f',
                ItemId: null,
                IsProcessed: false,
                OriginalValue: 'Mastey',
                ProposedValue: 'Last',
                ActionTaken: null,
                Status: null,
                SectionName: 'Name - last_name',
                RequestedDate: '9/3/2020 5:10:03 AM',
                RequestedBy: 'kgannonjedi+ref1025t@gmail.com',
                JoinedAuditItemId: null,
                ProposedEmailValue: null,
              },
            ],
            JoinedAudtItem: null,
          },
        ],
        Total: 0,
        HasOneAcceptedAddress: false,
        HasAboutMeAudit: false,
        HasFacilityAudit: false,
      },
    },
  ],
  removeAuditProvider,
};

const auditProviderList = {
  TotalRecords: 5,
  Results: [
    {
      ProviderAddress: '790 Minot Ave, Auburn, ME 04210',
      Type: 'Standard',
      AuditId: 570349,
      Pwid: '3CR4M',
      Status: 'READY',
      ProviderFullName: 'Dr. Michael F. Regan, Sr, MD',
      ClientName: null,
      UserName: 'mich@hgweb.com',
      AuditedByUsername: 'sadem',
      SubmittedByFullName: 'Michael Regan',
      LastModifiedDate: '2020-09-23T04:43:18.203',
      LastContactedDate: null,
      LastModifiedDateString: 'Wed, September 23, 2020',
      LastModifiedTimeString: '04:43 AM',
      ProfileManagerAuditRecord: {
        AuditSection: [
          {
            Id: null,
            Pwid: '3CR4M',
            IsProcessed: false,
            SectionName: 'AboutMe',
            Items: [
              {
                Id: '4a9d8b20-5b86-4d28-90d4-2e9deec12038',
                ItemId: 'About',
                IsProcessed: false,
                OriginalValue:
                  '<strong>Title:</strong> About Dr. Regan<p>Test Test</p>',
                ProposedValue:
                  '<strong>Title:</strong> About Dr. Regan<p>Demo Testing</p>',
                ActionTaken: 'REJECTED',
                Status: 'NEW',
                SectionName: 'Biography',
                RequestedDate: '11/9/2020 2:07:48 AM',
                RequestedBy: 'mich@hgweb.com',
                JoinedAuditItemId: 'About',
                ProposedEmailValue: null,
                AuditId: 235868,
              },
              {
                Id: 'd3b75e7a-a42a-4200-9386-90ddf39a019b',
                ItemId: 'CarePhilosophy',
                IsProcessed: false,
                OriginalValue: '<p>We Test..</p>',
                ProposedValue: '<p>Testing By Demo</p>',
                ActionTaken: 'READY',
                Status: 'NEW',
                SectionName: 'Care Philosophy',
                RequestedDate: '11/9/2020 2:33:39 AM',
                RequestedBy: 'mich@hgweb.com',
                JoinedAuditItemId: 'CarePhilosophy',
                ProposedEmailValue: null,
                AuditId: 235869,
              },
              {
                Id: 'b732c48b-857e-4d73-8ff0-422d213dc2bf',
                ItemId: 'ResponseToPes',
                IsProcessed: false,
                OriginalValue: '<strong>Unchanged</strong>',
                ProposedValue: '<p>test</p>',
                ActionTaken: 'READY',
                Status: 'SAME',
                SectionName: 'Response to Patient Satisfaction Surveys',
                RequestedDate: '9/23/2020 1:02:19 AM',
                RequestedBy: 'mich@hgweb.com',
                JoinedAuditItemId: 'ResponseToPes',
                ProposedEmailValue: null,
                AuditId: 0,
              },
            ],
            JoinedAudtItem: {
              Id: '12a0a208-c5b5-41b1-9daa-96b8e3727dd5',
              ItemId: 'CarePhilosophy',
              IsProcessed: false,
              OriginalValue: '<p>We Test..</p>',
              ProposedValue: 'Deleted',
              ActionTaken: 'HOLD',
              Status: 'DELETE',
              SectionName: 'Care Philosophy',
              RequestedDate: '9/23/2020 1:02:19 AM',
              RequestedBy: 'mich@hgweb.com',
              JoinedAuditItemId: null,
              ProposedEmailValue: null,
              AuditId: 235869,
            },
          },
          {
            Id: '1a0559a4-0375-4ad1-a75e-a665ab4dd62f',
            Pwid: '3CR4M',
            IsProcessed: false,
            SectionName: 'Video',
            Items: [
              {
                ItemId: null,
                IsProcessed: false,
                OriginalValue:
                  'https://testaws.healthgrades.com/video/00000153-8588-d304-afdf-ddec91bb0000',
                ProposedValue:
                  'https://d2074hyx2donso.cloudfront.net/videos/XYLTS6V/01f53e4a40444e978f6d355f238b42c1.mp4',
                ActionTaken: null,
                Status: null,
                SectionName: 'Video',
                AuditId: 54362,
                VideoDetails: {
                  ModerationResult: [
                    {
                      ModerationLabelName: 'Violence',
                      Timestamp: 5999,
                    },
                    {
                      ModerationLabelName: 'Weapon Violence',
                      Timestamp: 6499,
                    },
                    {
                      ModerationLabelName: 'Violence',
                      Timestamp: 25066,
                    },
                    {
                      ModerationLabelName: 'Weapon',
                      Timestamp: 25566,
                    },
                    {
                      ModerationLabelName: 'Violence',
                      Timestamp: 26066,
                    },
                    {
                      ModerationLabelName: 'Weapon',
                      Timestamp: 26566,
                    },
                    {
                      ModerationLabelName: 'Violence',
                      Timestamp: 27066,
                    },
                    {
                      ModerationLabelName: 'Weapons',
                      Timestamp: 27566,
                    },
                    {
                      ModerationLabelName: 'Weapon Violence',
                      Timestamp: 37566,
                    },
                    {
                      ModerationLabelName: 'Weapon Violence',
                      Timestamp: 38400,
                    },
                  ],
                  VideoTranscript:
                    "Where's friend free? She's at the tower with your little friend Marie Elka. She gave us a message to pass on to you. You have to choose the lesser evil. It's an ultimatum, get it, mm. Mhm. Yeah. Mhm. Okay. Mhm. Uh huh. Yeah. Yeah.",
                  VideoHostCode: 'BRIGHTSPOT',
                },
              },
            ],
            JoinedAudtItem: null,
          },
        ],
        Total: 1,
        HasOneAcceptedAddress: false,
        HasAboutMeAudit: false,
        HasFacilityAudit: false,
      },
    },
    {
      ProviderAddress: '2500 Ridge Ave, Evanston, IL 60201',
      Type: 'Sponsored',
      AuditId: 569924,
      Pwid: '33L3G',
      Status: 'READY',
      ProviderFullName: 'Polly S.  Reese',
      ClientName: 'WEO Media',
      UserName: 'sadem',
      AuditedByUsername: 'sadem',
      SubmittedByFullName: 'Sandeep Adem',
      LastModifiedDate: '2020-09-23T06:55:14.033',
      LastContactedDate: '2019-12-19T17:27:45.207',
      LastModifiedDateString: 'Wed, September 23, 2020',
      LastModifiedTimeString: '06:55 AM',
      ProfileManagerAuditRecord: {
        AuditSection: [],
        Total: 0,
        HasOneAcceptedAddress: false,
        HasAboutMeAudit: false,
        HasFacilityAudit: false,
      },
    },
    {
      ProviderAddress: '999 18th St, Denver, CO 80202',
      Type: 'Standard',
      AuditId: 566941,
      Pwid: 'YC7CH',
      Status: 'READY',
      ProviderFullName: 'Cindi T.  Rife (Test Profile), CFMP',
      ClientName: null,
      UserName: 'kgannonjedi+ref1025t@gmail.com',
      AuditedByUsername: 'sadem',
      SubmittedByFullName: 'Cindi Rife',
      LastModifiedDate: '2020-10-15T12:34:13.853',
      LastContactedDate: null,
      LastModifiedDateString: 'Thu, October 15, 2020',
      LastModifiedTimeString: '12:34 PM',
      ProfileManagerAuditRecord: {
        AuditSection: [
          {
            Id: null,
            Pwid: 'YC7CH',
            IsProcessed: false,
            SectionName: 'Education',
            Items: [
              {
                Id: '787daa6b-f21b-46d7-acfe-bb4e1ef4ae0a',
                ItemId: null,
                IsProcessed: false,
                OriginalValue: 'Cu ',
                ProposedValue: '',
                ActionTaken: 'HOLD',
                Status: 'DELETE',
                SectionName: 'Education - EDUTRA',
                RequestedDate: '4/10/2020 6:46:41 AM',
                RequestedBy: 'kgannonjedi+ref1025t@gmail.com',
                JoinedAuditItemId: null,
                ProposedEmailValue: null,
                AuditId: 233248,
              },
            ],
            JoinedAudtItem: null,
          },
          {
            Id: null,
            Pwid: 'YC7CH',
            IsProcessed: false,
            SectionName: 'AboutMe',
            Items: [
              {
                Id: '7b967000-40d7-4f37-8d41-597b8efc024e',
                ItemId: 'About',
                IsProcessed: false,
                OriginalValue:
                  '<strong>Title:</strong> About Cindi Rife (Test Profile)<p>Dr. Cindi&nbsp;Rife, MD is a psychiatry doctor who practices in Upland, PA. He has been practicing for 11 years. Dr. Glushakow is affiliated with Delaware County Memorial Hospital, Crozer - Chester Medical Center, Rife&nbsp;Hospital and Springfield Hospital.</p>',
                ProposedValue:
                  '<strong>Title:</strong> About Cindi Rife (Test Profile)<p>Demo message, just making it longer so it stands out</p>',
                ActionTaken: 'REJECTED',
                Status: 'NEW',
                SectionName: 'Biography',
                RequestedDate: '11/9/2020 8:28:27 PM',
                RequestedBy: 'kgannonjedi+ref1025t@gmail.com',
                JoinedAuditItemId: 'About',
                ProposedEmailValue: null,
                AuditId: 235987,
              },
              {
                Id: '68701757-8ce1-457d-a079-48dc434a38c0',
                ItemId: 'CarePhilosophy',
                IsProcessed: false,
                OriginalValue: '',
                ProposedValue:
                  '<p>Dr. Cindi&nbsp;Rife, MD is a psychiatry doctor who practices in Upland, PA. He has been practicing for 11 years. Dr. Glushakow is affiliated with Delaware County Memorial Hospital, Crozer - Chester Medical Center, Rife&nbsp;Hospital and Springfield Hospital.</p>',
                ActionTaken: 'HOLD',
                Status: 'NEW',
                SectionName: 'Care Philosophy',
                RequestedDate: '10/15/2020 12:34:13 PM',
                RequestedBy: 'kgannonjedi+ref1025t@gmail.com',
                JoinedAuditItemId: 'CarePhilosophy',
                ProposedEmailValue: null,
                AuditId: 235988,
              },
              {
                Id: 'c7284d36-ebc0-43ea-bda3-53ffd56ffa69',
                ItemId: 'ResponseToPes',
                IsProcessed: false,
                OriginalValue: '<p>testing 123</p>',
                ProposedValue: '<p>Test Response</p>',
                ActionTaken: 'HOLD',
                Status: 'NEW',
                SectionName: 'Response to Patient Satisfaction Surveys',
                RequestedDate: '10/15/2020 12:34:13 PM',
                RequestedBy: 'kgannonjedi+ref1025t@gmail.com',
                JoinedAuditItemId: 'ResponseToPes',
                ProposedEmailValue: null,
                AuditId: 235989,
              },
            ],
            JoinedAudtItem: {
              Id: '3d630837-56a7-434d-bfd8-72d608f76f81',
              ItemId: 'ResponseToPes',
              IsProcessed: false,
              OriginalValue: '<p>testing 123</p>',
              ProposedValue: 'Deleted',
              ActionTaken: 'HOLD',
              Status: 'DELETE',
              SectionName: 'Response to Patient Satisfaction Surveys',
              RequestedDate: '10/15/2020 12:34:13 PM',
              RequestedBy: 'kgannonjedi+ref1025t@gmail.com',
              JoinedAuditItemId: null,
              ProposedEmailValue: null,
              AuditId: 235989,
            },
          },
        ],
        Total: 2,
        HasOneAcceptedAddress: false,
        HasAboutMeAudit: false,
        HasFacilityAudit: false,
      },
    },
    {
      ProviderAddress: '320 Central Park W Ste 1-E, New York, NY 10025',
      Type: 'Standard',
      AuditId: 570846,
      Pwid: '32F9F',
      Status: 'READY',
      ProviderFullName: 'Dr. Harry J.  Aaron, MD',
      ClientName: null,
      UserName: 'dinatest@hgweb.com',
      AuditedByUsername: 'sadem',
      SubmittedByFullName: 'Dina Test',
      LastModifiedDate: '2020-10-24T09:31:37.807',
      LastContactedDate: null,
      LastModifiedDateString: 'Sat, October 24, 2020',
      LastModifiedTimeString: '09:31 AM',
      ProfileManagerAuditRecord: {
        AuditSection: [
          {
            Id: 'dacbec1b-8fe3-46ae-b0c6-5218edf0d7df',
            Pwid: '32F9F',
            IsProcessed: false,
            SectionName: 'Photo',
            Items: [
              {
                Id: 'dacbec1b-8fe3-46ae-b0c6-5218edf0d7df',
                ItemId: null,
                IsProcessed: false,
                OriginalValue:
                  '//d1ffafozi03i4l.cloudfront.net/img/prov/3/2/F/32F9F_w120h160.jpg',
                ProposedValue:
                  'http://update-alpha-testaws.healthgrades.com/image/32F9F/cropped',
                ActionTaken: 'HOLD',
                Status: null,
                SectionName: 'Photo',
                RequestedDate: '10/16/2020 5:31:12 AM',
                RequestedBy: 'dinatest@hgweb.com',
                JoinedAuditItemId: null,
                ProposedEmailValue: null,
                AuditId: 235991,
              },
            ],
            JoinedAudtItem: null,
          },
        ],
        Total: 1,
        HasOneAcceptedAddress: false,
        HasAboutMeAudit: false,
        HasFacilityAudit: false,
      },
    },
    {
      ProviderAddress: '531 Faunce Corner Rd, N Dartmouth, MA 02747',
      Type: 'Standard',
      AuditId: 570230,
      Pwid: 'Y2Y9R',
      Status: 'READY',
      ProviderFullName: 'Aldo-N A. Ciccotelli, Sr',
      ClientName: null,
      UserName: 'aldo@hgweb.com',
      AuditedByUsername: 'sadem',
      SubmittedByFullName: 'Aldo Ciccotelli',
      LastModifiedDate: '2020-10-26T21:51:21.517',
      LastContactedDate: null,
      LastModifiedDateString: 'Mon, October 26, 2020',
      LastModifiedTimeString: '09:51 PM',
      ProfileManagerAuditRecord: {
        AuditSection: [
          {
            Id: null,
            Pwid: 'Y2Y9R',
            IsProcessed: false,
            SectionName: 'AboutMe',
            Items: [
              {
                Id: '8ca07d9b-4f4c-4b0c-9eaf-841612b95757',
                ItemId: 'About',
                IsProcessed: false,
                OriginalValue:
                  '<strong>Title:</strong> About Aldo-N Ciccotelli Sr<p>Health is Wealth, and cannot be purchased</p>',
                ProposedValue:
                  '<strong>Title:</strong> About Aldo-N Ciccotelli Sr<p>Biography Testing</p>',
                ActionTaken: 'READY',
                Status: 'NEW',
                SectionName: 'Biography',
                RequestedDate: '10/22/2020 10:27:13 PM',
                RequestedBy: 'aldo@hgweb.com',
                JoinedAuditItemId: 'About',
                ProposedEmailValue: null,
                AuditId: 235960,
              },
              {
                Id: 'c0a54a10-ed76-4226-b85d-5d10fdc030a6',
                ItemId: 'CarePhilosophy',
                IsProcessed: false,
                OriginalValue: '<p>Providing good care</p>',
                ProposedValue: '<p>Care Philosophy testing</p>',
                ActionTaken: 'READY',
                Status: 'NEW',
                SectionName: 'Care Philosophy',
                RequestedDate: '10/24/2020 2:44:16 AM',
                RequestedBy: 'aldo@hgweb.com',
                JoinedAuditItemId: 'CarePhilosophy',
                ProposedEmailValue: null,
                AuditId: 235961,
              },
              {
                Id: 'd176e864-1b06-4ef1-b6db-c608d755e471',
                ItemId: 'ResponseToPes',
                IsProcessed: false,
                OriginalValue: '<strong>Unchanged</strong>',
                ProposedValue: '<p>Happy to serve</p>',
                ActionTaken: 'READY',
                Status: 'SAME',
                SectionName: 'Response to Patient Satisfaction Surveys',
                RequestedDate: '9/28/2020 4:28:47 AM',
                RequestedBy: 'aldo@hgweb.com',
                JoinedAuditItemId: 'ResponseToPes',
                ProposedEmailValue: null,
                AuditId: 0,
              },
            ],
            JoinedAudtItem: {
              Id: '849b3d50-6f9e-4b88-a7fc-9d2c015fea04',
              ItemId: 'CarePhilosophy',
              IsProcessed: false,
              OriginalValue: '<p>Providing good care</p>',
              ProposedValue: 'Deleted',
              ActionTaken: 'HOLD',
              Status: 'DELETE',
              SectionName: 'Care Philosophy',
              RequestedDate: '9/28/2020 4:28:47 AM',
              RequestedBy: 'aldo@hgweb.com',
              JoinedAuditItemId: null,
              ProposedEmailValue: null,
              AuditId: 235961,
            },
          },
        ],
        Total: 1,
        HasOneAcceptedAddress: false,
        HasAboutMeAudit: false,
        HasFacilityAudit: false,
      },
    },
  ],
};

storiesOf('AuditProviderList', module)
  .addDecorator((story) => <AdminStore story={story()} />)
  .add('AuditProviderList', () => <AuditProviderList {...auditProviderList} />);
