import React from 'react';
import AuditProvider from '../AuditProvider';
import { storiesOf } from '@storybook/react';


const auditProvider = {
  ProviderAddress: '999 18th St, Denver, CO 80202',
  Type: 'Sponsored',
  AuditId: 566941,
  Pwid: 'YC7CH',
  Status: 'READY',
  ProviderFullName: 'Cindi T.  Rife (Test Profile), CFMP',
  ClientName: 'Metro Regional Medical Center Testing and Demo',
  UserName: 'kgannonjedi+ref1025t@gmail.com',
  AuditedByUsername: 'Test',
  SubmittedByFullName: 'Cindi Rife',
  LastModifiedDate: '2020-09-15T07:11:16.48',
  LastContactedDate: null,
  ProfileManagerAuditRecord: {
    AuditSection: [
      {
        Id: '8818fd9c-2d34-4de2-9925-42c604396ba6',
        Pwid: 'YC7CH',
        IsProcessed: false,
        SectionName: 'Name - first_name',
        Items: [
          {
            Id: '8818fd9c-2d34-4de2-9925-42c604396ba6',
            ItemId: null,
            IsProcessed: false,
            OriginalValue: 'Cindi',
            ProposedValue: 'C',
            ActionTaken: null,
            Status: null,
            SectionName: 'Name - first_name',
            RequestedDate: '9/3/2020 5:10:03 AM',
            RequestedBy: 'kgannonjedi+ref1025t@gmail.com',
            JoinedAuditItemId: null,
            ProposedEmailValue: null,
          },
        ],
        JoinedAudtItem: null,
      },
      {
        Id: '1a0559a4-0375-4ad1-a75e-a215ab4dd62f',
        Pwid: 'YC7CH',
        IsProcessed: false,
        SectionName: 'Name - last_name',
        Items: [
          {
            Id: '1a0559a4-0375-4ad1-a75e-a215ab4dd62f',
            ItemId: null,
            IsProcessed: false,
            OriginalValue: 'Last',
            ProposedValue: 'R',
            ActionTaken: null,
            Status: null,
            SectionName: 'Name - last_name',
            RequestedDate: '9/3/2020 5:10:03 AM',
            RequestedBy: 'kgannonjedi+ref1025t@gmail.com',
            JoinedAuditItemId: null,
            ProposedEmailValue: null,
          },
        ],
        JoinedAudtItem: null,
      },
      {
        Id: '4ee9021a-a342-45b9-bbd0-81307774772b',
        Pwid: 'YC7CH',
        IsProcessed: false,
        SectionName: 'License',
        Items: [
          {
            Id: '4ee9021a-a342-45b9-bbd0-81307774772b',
            ItemId: null,
            IsProcessed: false,
            OriginalValue: 'AL 55461e',
            ProposedValue: '',
            ActionTaken: null,
            Status: 'DELETE',
            SectionName: 'License - DELETE',
            RequestedDate: '4/10/2020 6:12:47 AM',
            RequestedBy: 'kgannonjedi+ref1025t@gmail.com',
            JoinedAuditItemId: null,
            ProposedEmailValue: null,
          },
        ],
        JoinedAudtItem: null,
      },
      {
        Id: 'aff01488-fcce-4944-9873-7c576033a22b',
        Pwid: 'YC7CH',
        IsProcessed: false,
        SectionName: 'License',
        Items: [
          {
            Id: 'aff01488-fcce-4944-9873-7c576033a22b',
            ItemId: null,
            IsProcessed: false,
            OriginalValue: '',
            ProposedValue: 'CA ',
            ActionTaken: null,
            Status: 'NEW',
            SectionName: 'License - NEW',
            RequestedDate: '4/10/2020 6:12:47 AM',
            RequestedBy: 'kgannonjedi+ref1025t@gmail.com',
            JoinedAuditItemId: null,
            ProposedEmailValue: null,
          },
        ],
        JoinedAudtItem: null,
      },
      {
        Id: '90b7b62c-6522-4114-9aa5-b3554a5252bf',
        Pwid: 'YC7CH',
        IsProcessed: false,
        SectionName: 'AboutMe',
        Items: [
          {
            Id: '90b7b62c-6522-4114-9aa5-b3554a5252bf',
            ItemId: 'About',
            IsProcessed: false,
            OriginalValue:
              '<strong>Title:</strong> About Cindi Rife (Test Profile)<p>Dr. Cindi&nbsp;Rife, MD is a psychiatry doctor who practices in Upland, PA. He has been practicing for 11 years. Dr. Glushakow is affiliated with Delaware County Memorial Hospital, Crozer - Chester Medical Center, Rife&nbsp;Hospital and Springfield Hospital.</p>',
            ProposedValue:
              '<strong>Title:</strong> About Cindi Rife (Test Profile)<p>Demo</p>',
            ActionTaken: 'HOLD',
            Status: 'NEW',
            SectionName: 'Biography',
            RequestedDate: '9/3/2020 5:10:11 AM',
            RequestedBy: 'kgannonjedi+ref1025t@gmail.com',
            JoinedAuditItemId: 'About',
            ProposedEmailValue: null,
          },
        ],
        JoinedAudtItem: {
          Id: 'ba4c8e85-e8f1-455b-9c2a-2b7dca5c1a28',
          ItemId: 'About',
          IsProcessed: false,
          OriginalValue:
            '<strong>Title:</strong> About Cindi Rife (Test Profile)<p>Dr. Cindi&nbsp;Rife, MD is a psychiatry doctor who practices in Upland, PA. He has been practicing for 11 years. Dr. Glushakow is affiliated with Delaware County Memorial Hospital, Crozer - Chester Medical Center, Rife&nbsp;Hospital and Springfield Hospital.</p>',
          ProposedValue: 'Deleted',
          ActionTaken: 'HOLD',
          Status: 'DELETE',
          SectionName: 'Biography',
          RequestedDate: '9/3/2020 5:10:11 AM',
          RequestedBy: 'kgannonjedi+ref1025t@gmail.com',
          JoinedAuditItemId: null,
          ProposedEmailValue: null,
        },
      },
      {
        Id: '78979230-4a5a-49a2-9265-c20537d3ec58',
        Pwid: 'YC7CH',
        IsProcessed: false,
        SectionName: 'AboutMe',
        Items: [
          {
            Id: '78979230-4a5a-49a2-9265-c20537d3ec58',
            ItemId: 'CarePhilosophy',
            IsProcessed: false,
            OriginalValue: '',
            ProposedValue:
              '<p>Dr. Cindi&nbsp;Rife, MD is a psychiatry doctor who practices in Upland, PA. He has been practicing for 11 years. Dr. Glushakow is affiliated with Delaware County Memorial Hospital, Crozer - Chester Medical Center, Rife&nbsp;Hospital and Springfield Hospital.</p>',
            ActionTaken: 'HOLD',
            Status: 'NEW',
            SectionName: 'Care Philosophy',
            RequestedDate: '9/3/2020 5:10:11 AM',
            RequestedBy: 'kgannonjedi+ref1025t@gmail.com',
            JoinedAuditItemId: 'CarePhilosophy',
            ProposedEmailValue: null,
          },
        ],
        JoinedAudtItem: null,
      },
      {
        Id: '224abcc0-a60f-457f-b0de-3b09f1f5a18d',
        Pwid: 'YC7CH',
        IsProcessed: false,
        SectionName: 'AboutMe',
        Items: [
          {
            Id: '224abcc0-a60f-457f-b0de-3b09f1f5a18d',
            ItemId: 'ResponseToPes',
            IsProcessed: false,
            OriginalValue: '<p>testing 123</p>',
            ProposedValue: '<p>Test Response</p>',
            ActionTaken: 'HOLD',
            Status: 'NEW',
            SectionName: 'Response to Patient Satisfaction Surveys',
            RequestedDate: '9/3/2020 5:10:11 AM',
            RequestedBy: 'kgannonjedi+ref1025t@gmail.com',
            JoinedAuditItemId: 'ResponseToPes',
            ProposedEmailValue: null,
          },
        ],
        JoinedAudtItem: {
          Id: '96890014-51c4-4a43-a868-19b477b35b98',
          ItemId: 'ResponseToPes',
          IsProcessed: false,
          OriginalValue: '<p>testing 123</p>',
          ProposedValue: 'Deleted',
          ActionTaken: 'HOLD',
          Status: 'DELETE',
          SectionName: 'Response to Patient Satisfaction Surveys',
          RequestedDate: '9/3/2020 5:10:11 AM',
          RequestedBy: 'kgannonjedi+ref1025t@gmail.com',
          JoinedAuditItemId: null,
          ProposedEmailValue: null,
        },
      },
    ],
    Total: 0,
    HasOneAcceptedAddress: true,
    HasAboutMeAudit: true,
    HasFacilityAudit: false,
  },
};
storiesOf('AuditProvider', module).add('AuditProvider', () => (
  <AuditProvider {...auditProvider} />
));
